shared:
  image: node:10
annotations:
  screwdriver.cd/restrictPR: all
jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - echo: echo main
  sub:
    requires: [~pr, ~commit]
    steps:
      - echo: echo sub
