childPipelines:
  scmUrls:
    - git@github.com:yokawara/sd-test-child-pipeline.git

shared:
  image: node:10
jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - echo1: echo first
      - echo2: echo second
      - sleep: sleep 60
      - echo3: echo third
  branch:
    requires: [~pr:branch]
    steps:
      - echo: echo "triggered by ~pr:branch"
  after-branch:
    requires: [branch]
    steps:
      - echo: echo "triggered by branch job"
