shared:
  image: node:10
annotations:
  screwdriver.cd/restrictPR: all
jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - echo1: echo first
      - echo2: echo second
      - sleep: sleep 60
      - echo3: echo third
