# childPipelines:
#   scmUrls:
#     - git@github.com:yokawara/sd-test-child-pipeline.git#master

parameters:
  param: "sample-parameter"

shared:
  image: node:10
jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - echo1: echo first
      - parameter: echo `meta get parameters.param.value`
  branch:
    requires: [~pr:branch]
    steps:
      - echo: echo "triggered by ~pr:branch"
  after-branch:
    requires: [branch]
    steps:
      - echo: echo "triggered by branch job"
